### ISSUE TITLE
GitHub Tests Workflow Suggestion

### ISSUE THREAD

**Issue by renja-g** [iann838/pulsefire#11]
What are your thoughts on a GitHub Workflow that runs the test on `push` and `pull_request`.
It's hard for contributors to run the tests, since you need all the API_KEYS. But with GitHub workflows, you could define the keys in your project secrets.

**Comment by iann838** [comment]
Yes, I had this thought yesterday, will be assessing the requirements first

**Comment by iann838** [comment]
2 workflows has been added, one for runtime tests, and one for schemas tests (this one runs on schedule only)
