### ISSUE TITLE
[Request] Spectator v5 endpoints

### ISSUE THREAD

**Issue by Aluerie** [iann838/pulsefire#6]
There are new endpoints that library needs to add. I might try PRing it myself, but they say spectator-v4 will be deprecated in April so I guess, it's rather important to add new endpoints asap so I decided to highlight it with submitting an issue. These endpoints are using puuids and thus are very nice 😁 

## `Spectator-v5`:
* [/lol/spectator/v5/active-games/by-summoner/{encryptedPUUID}](https://developer.riotgames.com/apis#spectator-v5/GET_getCurrentGameInfoByPuuid)
* [/lol/spectator/v5/featured-games](https://developer.riotgames.com/apis#spectator-v5/GET_getFeaturedGames)

## `Spectator-tft-v5`
* [/lol/spectator/tft/v5/active-games/by-puuid/{encryptedPUUID}](https://developer.riotgames.com/apis#spectator-tft-v5/GET_getCurrentGameInfoByPuuid)
* [/lol/spectator/tft/v5/featured-games](https://developer.riotgames.com/apis#spectator-tft-v5/GET_getFeaturedGames)

## Related RiotGamesDevRel's tweets
* https://x.com/RiotGamesDevRel/status/1764780016640852222
* https://x.com/RiotGamesDevRel/status/1764780018025083163
* https://x.com/RiotGamesDevRel/status/1768386870617030891

**Comment by iann838** [comment]
@Aluerie Thanks for letting me know, if you can submit a PR it is much appreciated.

**Comment by renja-g** [comment]
Hey @iann838 v4 is already deprecated. If you want, I can make the PR, just tell me if I should replace V4 with V5 or add V5?
Also, is there a pattern how you sort the schema keys?

**Comment by iann838** [comment]
@renja-g It went off my mind, I'll do it today, after my appointment I have today, should be relatively quick.

**Comment by iann838** [comment]
It should be good with v2.0.9, if it's not supported please reopen the issue, TFT spectator was not supported before, therefore it is not part of this commit and will likely not be supported due to lack of interest, if you want TFT spectator support, please open a PR instead.
